name: Build & Deploy Docker Containers
on:
  # Build on push to any branch
  push: []

jobs:
  deploy-images:
    runs-on: ubuntu-latest
    environment: Deployment
    strategy:
      fail-fast: false
      # Just build primary Dockerfile, tag, arm and amd64 for now
      matrix:
        dockerfile: [[Dockerfile, 'linux/amd64', ''], ["Dockerfile.arm", 'linux/arm64', '-arm64']]

    name: Build ${{ matrix.dockerfile[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Container Tag
        run: |
          branch=$(echo ${GITHUB_REF##*/})
          printf "Branch is ${branch}\n"
          tagged="ghcr.io/schillingalex/singularity-docker:${branch}${{ matrix.dockerfile[2] }}"
          if [[ "${branch}" == "master" ]]; then
              container="ghcr.io/schillingalex/singularity-docker:latest${{ matrix.dockerfile[2] }}"
          else
              container=${tagged}
          fi
          echo "container=${container}" >> $GITHUB_ENV
          echo "branch=${branch}" >> $GITHUB_ENV
          echo "tagged=${tagged}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect Container Names
        run: |
          printf "Tagged: ${tagged}\n"        
          printf "Container: ${container}\n"  

      - name: Build
        uses: docker/build-push-action@v5
        if: github.event_name != 'push'
        with:
          file: ${{matrix.dockerfile[0]}}
          platforms: ${{ matrix.dockerfile[1] }}
          push: false
          tags: |
            ${{ env.container }}
            ${{ env.tagged }}

      - name: Build & Deploy
        uses: docker/build-push-action@v5
        if: github.event_name == 'push'
        with:
          file: ${{matrix.dockerfile[0]}}
          platforms: ${{ matrix.dockerfile[1] }}
          push: true
          tags: |
            ${{ env.container }}
            ${{ env.tagged }}
